apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitea
  namespace: gitea
spec:
  namespaceSelector:
    matchNames:
      - gitea
  selector:
    matchLabels:
      app: gitea
  endpoints:
  - port: prometheus
    path: /
    interval: 5s