{%- from "kubernetes/map.jinja" import common with context -%}
{%- from "kubernetes/map.jinja" import master with context -%}

apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    k8s-app: kube-scheduler
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: {{ common.image }}
    command:
    - /hyperkube
    - scheduler
    - --config=/var/lib/kube-scheduler/kube-scheduler-config.yaml
    - --v=2
    resources:
      requests:
        cpu: 100m
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: /etc/kubernetes
      name: config-kubernetes
      readOnly: true
    - mountPath: /var/lib/kube-scheduler
      name: config-kube-scheduler
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: config-kubernetes
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
  - hostPath:
      path: /var/lib/kube-scheduler
    name: config-kube-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler
  namespace: kube-system
  annotations:
    prometheus.io/port: "10252"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: kube-scheduler
spec:
  selector:
    k8s-app: kube-scheduler
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP