kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: velero
  namespace: velero
spec:
  endpoints:
    - interval: 30s
      port: monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/name: velero
