ory:
  hydra:
    version: 1.4.6
    ingress_host: oauth
    # export LC_CTYPE=C; cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
    system_secret: 2EYfY6MWHd3pXUkqeb3DrPjpsxe6p67i
    cookie_secret: uJd8AOqKyui6PmT54xa34cI52csbwmu6
    dsn: memory