{%- set public_domain = pillar['public-domain'] -%}
{%- from "kubernetes/map.jinja" import common with context -%}

{%- if common.addons.get('ingress_traefik', {'enabled': False}).enabled %}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
spec:
  rules:
  - host: sso.{{ public_domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak-http
          servicePort: 80
---
{% endif %}

{%- if common.addons.get('ingress_istio', {'enabled': False}).enabled -%}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
  namespace: default
spec:
  gateways:
  - istio-gateway
  hosts:
  - sso.{{ public_domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: keycloak-http.keycloak.svc.cluster.local
        port:
          number: 80
---
{% endif %}