controller:
  daemonset:
    useHostPort: true
    hostPorts:
      http: 80
      https: 443
  kind: DaemonSet
  nodeSelector:
    node-role.kubernetes.io/ingress: "true"
  tolerations:
    - key: node-role.kubernetes.io/ingress
      effect: NoSchedule
  stats:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
defaultBackend:
  enabled: true
  replicaCount: 2
rbac:
  create: true
serviceAccount:
  create: true