calico:
  node_image: docker.io/calico/node:v3.14.1
  typha_image: docker.io/calico/typha:v3.14.1
  cni_image: docker.io/calico/cni:v3.14.1
  controller_image: docker.io/calico/kube-controllers:v3.14.1
  flexvol_image: docker.io/calico/pod2daemon-flexvol:v3.14.1
  version: 3.14.1
  mtu: 1430
  ipv4:
    range: 10.244.0.0/16
    nat: true
    ip_in_ip: always
    interface: eth0
  ipv6:
    enable: false
    nat: true
    interface: eth0
    range: fd80:24e2:f998:72d6::/64