spinnaker:
  version: 1.18.4
  halyard_version: 1.29.0
  ingress_host: spinnaker
  minio_image: docker.io/minio/minio:RELEASE.2020-01-03T19-12-21Z
  # github:
  #   enabled: True
  #   token: 0123456789abcdefghij0123456789abcdefghij
  # s3:
  #   accesskey: spinnaker
  #   secretkey: Sp1nn4k3rS3cr3tK3y
  #   bucket: spinnaker
  # oauth:
  #   provider: keycloak
  #   keycloak:
  #     realm: default
  # concourse:
  #   username: spinnaker
  #   password: 1nt3gr4t1on