# Select any services with the prometheus:cockroachdb label
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cockroachdb
  namespace: ory
  labels:
    app.kubernetes.io/name: cockroachdb
spec:
  namespaceSelector:
    matchNames:
    - ory
  selector:
    matchLabels:
      app.kubernetes.io/name: cockroachdb
  endpoints:
  - port: http
    path: /_status/vars
    tlsConfig:
      # The HTTPS certs are signed by the kubernetes internal
      # certificate authority.
      caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      # This overrides the hostname verification check for the admin
      # UI port to match our quickstart secure-mode cluster setup.
      serverName: "127.0.0.1"
    metricRelabelings:
    - action: replace
      sourceLabels:
      - pod
      targetLabel: instance
    - action: replace
      sourceLabels:
      - service
      targetLabel: cluster