argo:
  workflow:
    version: 2.8.1
    image: argoproj/argocli:v2.8.1
  cd:
    version: 1.5.7
    image: docker.io/argoproj/argocd:v1.5.7
    dex_image: quay.io/dexidp/dex:v2.22.0
    redis_image: docker.io/amd64/redis:5.0.6-alpine
    haproxy_image: docker.io/amd64/haproxy:2.0.4
  username: argo
  password: 4rg0
  db_password: V3ry1ns3sur3P4ssw0rd
  db_size: 8Gi
  ingress_host: argo
  minio_image: docker.io/minio/minio:latest
  worker_capacity: 20Gi
  # oauth:
  #   provider: keycloak
  #   keycloak:
  #     realm: default
  # s3:
  #   accesskey: argo
  #   secretkey: C0nc0ur53P4ssw0rd
  #   bucket: argo