kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: rook-cockroachdb
  namespace: rook-cockroachdb
spec:
  endpoints:
    - interval: 30s
      port: http
      path: /metrcis
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/name: velero
