apiVersion: v1
kind: Pod
metadata:
  name: ceph-exporter
  namespace: rook-ceph
  labels:
    app: ceph-exporter
spec:
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: rook-ceph-tools
    image: rook/ceph-toolbox:master
    imagePullPolicy: IfNotPresent
    env:
      - name: ROOK_ADMIN_SECRET
        valueFrom:
          secretKeyRef:
            name: rook-ceph-mon
            key: admin-secret
    volumeMounts:
      - mountPath: /lib/modules
        name: libmodules
      - name: mon-endpoint-volume
        mountPath: /etc/rook
      - name: etc-ceph-shared
        mountPath: /etc/ceph
  - name: ceph-exporter
    image: digitalocean/ceph_exporter:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: ROOK_ADMIN_SECRET
        valueFrom:
          secretKeyRef:
            name: rook-ceph-mon
            key: admin-secret
    ports:
    - containerPort: 9128
      name: http-metrics
      protocol: TCP
    volumeMounts:
      - name: etc-ceph-shared
        mountPath: /etc/ceph
  hostNetwork: true
  volumes:
    - name: libmodules
      hostPath:
        path: /lib/modules
    - name: mon-endpoint-volume
      configMap:
        name: rook-ceph-mon-endpoints
        items:
        - key: data
          path: mon-endpoints
    - name: etc-ceph-shared
      emptyDir: {}

---
apiVersion: v1
kind: Service

metadata:
  labels:
    app: ceph-exporter
    rook_cluster: rook-ceph
  name: ceph-exporter
  namespace: rook-ceph
spec:
  ports:
  - name: http-metrics
    port: 9128
    protocol: TCP
    targetPort: 9128
  selector:
    app: ceph-exporter
  type: ClusterIP