{%- set hostname = salt['grains.get']('fqdn') -%}
{%- set hyperkubeImageRepo = pillar['kubernetes']['hyperkube-image-repo'] -%}
{%- set k8sVersion = pillar['kubernetes']['version'] -%}
{%- set clusterIpRange = pillar['kubernetes']['global']['service-ip-range'] -%}
{%- set etcd01ip = pillar['kubernetes']['etcd']['cluster']['etcd01']['ipaddr'] -%}
{%- set etcd02ip = pillar['kubernetes']['etcd']['cluster']['etcd02']['ipaddr'] -%}
{%- set etcd03ip = pillar['kubernetes']['etcd']['cluster']['etcd03']['ipaddr'] -%}
{%- set masterCount = pillar['kubernetes']['master']['count'] -%}
{%- set node01 = pillar['kubernetes']['master']['cluster']['node01']['hostname'] -%}
{%- set node02 = pillar['kubernetes']['master']['cluster']['node02']['hostname'] -%}
{%- set node03 = pillar['kubernetes']['master']['cluster']['node03']['hostname'] -%}
{%- set node01ip = pillar['kubernetes']['master']['cluster']['node01']['ipaddr'] -%}
{%- set node02ip = pillar['kubernetes']['master']['cluster']['node02']['ipaddr'] -%}
{%- set node03ip = pillar['kubernetes']['master']['cluster']['node03']['ipaddr'] -%}
{%- if hostname == node01 -%}
  {%- set currentip = node01ip -%}
{%- elif hostname == node02 -%}
  {%- set currentip = node02ip -%}
{%- elif hostname == node03 -%}
  {%- set currentip = node03ip -%}
{%- else %}
  {%- set currentip = "127.0.0.1" -%}
{%- endif -%}

apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: {{ hyperkubeImageRepo }}:{{ k8sVersion }}
    command:
    - /hyperkube
    - apiserver
    - --enable-admission-plugins=NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
    - --advertise-address={{ currentip }}
    - --allow-privileged=true
    - --anonymous-auth=false
    - --apiserver-count={{ masterCount }}
    - --audit-log-maxage=30
    - --audit-log-maxbackup=3
    - --audit-log-maxsize=100
    - --audit-log-path=/var/log/kube-audit/audit.log
    - --audit-policy-file=/etc/kubernetes/audit-policy.yaml
    - --authorization-mode=Node,RBAC
    - --bind-address=0.0.0.0
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --enable-bootstrap-token-auth
    - --enable-swagger-ui=true
    - --storage-backend=etcd3
    - --etcd-cafile=/etc/kubernetes/ssl/ca.pem
    - --etcd-certfile=/etc/kubernetes/ssl/apiserver.pem
    - --etcd-keyfile=/etc/kubernetes/ssl/apiserver-key.pem
    - --etcd-servers=https://{{ etcd01ip }}:2379,https://{{ etcd02ip }}:2379,https://{{ etcd03ip }}:2379
    - --event-ttl=1h
    # - --experimental-encryption-provider-config=/etc/kubernetes/encryption-config.yaml
    - --insecure-bind-address=127.0.0.1
    # https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authentication
    - --kubelet-certificate-authority=/etc/kubernetes/ssl/ca.pem
    - --kubelet-client-certificate=/etc/kubernetes/ssl/apiserver.pem
    - --kubelet-client-key=/etc/kubernetes/ssl/apiserver-key.pem
    - --kubelet-https=true
    - --runtime-config=api/all
    # - --runtime-config=extensions/v1beta1/networkpolicies=true
    - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --service-cluster-ip-range={{ clusterIpRange }}
    - --service-node-port-range=30000-50000
    - --storage-media-type=application/json
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --tls-ca-file=/etc/kubernetes/ssl/ca.pem
    - --token-auth-file=/etc/kubernetes/token.csv
    - --v=2
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: 6443
      hostPort: 6443
      name: https
    - containerPort: 7080
      hostPort: 7080
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: /etc/kubernetes
      name: config-kubernetes
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: config-kubernetes
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host