{%- set hyperkubeImageRepo =  pillar['kubernetes']['hyperkube-image-repo'] -%}
{%- set k8sVersion =  pillar['kubernetes']['version'] -%}

apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: {{ hyperkubeImageRepo }}:{{ k8sVersion }}
    command:
    - /hyperkube
    - scheduler
    - --address=0.0.0.0
    - --master=http://127.0.0.1:8080
    - --leader-elect=true
    - --v=2
    resources:
      requests:
        cpu: 100m
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 15