{%- from "kubernetes/map.jinja" import master with context -%}

kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: {{ master.encryption_key }}
      - identity: {}
