concourse:
  username: concourse
  password: C0nC0urs3
  db_password: V3ry1ns3sur3P4ssw0rd
  db_size: 8Gi
  version: 6.1.0
  source_hash: bec8cd95e950d818ab8ae7eafeb0aef117c965eb
  ingress_host: concourse
  minio_image: docker.io/minio/minio:latest
  # oauth:
  #   provider: keycloak
  #   keycloak:
  #     realm: default
  # s3:
  #   accesskey: concourse
  #   secretkey: C0nc0ur53P4ssw0rd
  #   bucket: concourse