{%- set public_domain = pillar['public-domain'] -%}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spinnaker
  namespace: default
spec:
  gateways:
  - istio-gateway
  hosts:
  - spinnaker.{{ public_domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: spin-deck.spinnaker.svc.cluster.local
        port:
          number: 9000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spinnaker-gate
  namespace: default
spec:
  gateways:
  - istio-gateway
  hosts:
  - spinnaker-gate.{{ public_domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: spin-gate.spinnaker.svc.cluster.local
        port:
          number: 8084