apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: concourse-web
  namespace: concourse
spec:
  namespaceSelector:
    matchNames:
      - concourse
  selector:
    matchLabels:
      app: concourse-web
  endpoints:
  - port: prometheus
    path: /
    interval: 5s