apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nuclio-system
  namespace: nuclio
spec:
  namespaceSelector:
    matchNames:
      - nuclio
  selector:
    matchLabels:
      nuclio.io/class: function
  endpoints:
  - port: metrics
    path: /metrics
    interval: 5s