{%- set public_domain = pillar['public-domain'] -%}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
spec:
  rules:
  - host: ceph.{{ public_domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: rook-ceph-mgr-dashboard-external
          servicePort: dashboard