{%- set public_domain = pillar['public-domain'] -%}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
  namespace: default
spec:
  gateways:
  - istio-gateway
  hosts:
  - sso.{{ public_domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: keycloak-http.keycloak.svc.cluster.local
        port:
          number: 80
