
rook_ceph:
  image: docker.io/rook/ceph:v1.3.5
  ceph_image: docker.io/ceph/ceph:v14.2.9
  exporter_image: digitalocean/ceph_exporter:latest
  ingress_host: ceph
  store_type: filestore
  timeout: 180
  default_storageclass:
    enabled: true
    name: rook-ceph-block
