apiVersion: v1
kind: Service
metadata:
  name: gateway-metrics
  namespace: openfaas
  labels:
    app: openfaas
    component: gateway
spec:
  ports:
  - name: metrics
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: gateway
  sessionAffinity: None
  type: ClusterIP