openfaas:
  client_version: 0.12.4
  client_source_hash: e31fd403a370f5fb668294a1b07b4307feeb724908c0618675ed342c66768359
  oauth2_image: alexellis2/openfaas-oidc-plugin:0.2.4
  nats_connector_image: openfaas/nats-connector:0.2.0
  ingress_host: openfaas
  username: admin
  password: V3ry1ns3cur3
  nats_topics: "nats_test,"
  oauth:
    enabled: False
    provider: keycloak
    keycloak:
      realm: default
