apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-ingress-lb
  namespace: monitoring
  labels:
    k8s-app: traefik-ingress-lb
spec:
  endpoints:
  - port: http
    path: /metrics
    interval: 5s
  selector:
    matchNames:
      - traefik-web-ui
  namespaceSelector:
    matchNames:
    - kube-system