{%- set public_domain = pillar['public-domain'] -%}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
  namespace: default
spec:
  gateways:
  - istio-gateway
  hosts:
  - prometheus.{{ public_domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: prometheus-k8s.monitoring.svc.cluster.local
        port:
          number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alertmanager
  namespace: default
spec:
  gateways:
  - istio-gateway
  hosts:
  - alertmanager.{{ public_domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: alertmanager-main.monitoring.svc.cluster.local
        port:
          number: 9093
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: default
spec:
  gateways:
  - istio-gateway
  hosts:
  - grafana.{{ public_domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: grafana.monitoring.svc.cluster.local
        port:
          number: 3000
---