apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: minio
spec:
  endpoints:
    - interval: 5s
      path: /minio/prometheus/metrics
      port: http-minio
  namespaceSelector:
    matchNames:
      - minio
  selector:
    matchLabels:
      app: minio
